"""Build and post JIRA QA report comments from Playwright test results."""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import TypedDict


class FailedTest(TypedDict):
    tc_id: str
    title: str
    error: str


class JiraReportWriter:
    """Compose a JIRA-formatted QA report comment.

    Usage:
        from scripts.jira_report_writer import JiraReportWriter

        body = JiraReportWriter().build_comment(
            feature="Checkout",
            tc_designed=10,
            tc_automated=8,
            passed=7,
            failed=1,
            skipped=0,
            spec_path="playwright-automation-framework/tests/e2e/checkout.spec.ts",
            flow_path="inputs/manual-flows/checkout.md",
            screen_map_path="playwright-automation-framework/support/screen-maps/checkout.screen.json",
            failed_tests=[{"tc_id": "TC_003", "title": "Place order", "error": "Timeout 30000ms"}],
        )
    """

    def build_comment(
        self,
        feature: str,
        *,
        tc_designed: int,
        tc_automated: int,
        passed: int,
        failed: int,
        skipped: int,
        spec_path: str,
        flow_path: str,
        screen_map_path: str,
        failed_tests: list[FailedTest] | None = None,
        executed_at: str | None = None,
    ) -> str:
        """Return a JIRA wiki-markup comment string."""
        verdict = "✅ PASS" if failed == 0 else "❌ FAIL"
        ts = executed_at or datetime.now(timezone.utc).isoformat()

        lines: list[str] = [
            f"🤖 *Automated QA Report* — {feature}",
            "━" * 40,
            "",
            "*Test Execution Summary*",
            "||Metric||Value||",
            f"|Test Cases Designed|{tc_designed}|",
            f"|Test Cases Automated|{tc_automated}|",
            f"|✅ Passed|{passed}|",
            f"|❌ Failed|{failed}|",
            f"|⏭ Skipped|{skipped}|",
            f"|Overall Verdict|{verdict}|",
            "",
            "*Artefacts*",
            f"* Input: {flow_path}",
            f"* Playwright Spec: {spec_path}",
            f"* Screen map: {screen_map_path}",
            f"* Executed: {ts}",
        ]

        if failed_tests:
            lines += [
                "",
                "---",
                "*Failed Tests*",
                "||TC||Test Title||Error||",
            ]
            for ft in failed_tests:
                lines.append(f"|{ft['tc_id']}|{ft['title']}|{ft['error']}|")

        lines += [
            "",
            "---",
            f"*Recommendation*",
            (
                "✅ All automated tests passed. Ready for review."
                if failed == 0
                else f"❌ {failed} test(s) failed. Investigate before merging."
            ),
            "",
            "_Report generated by AIQE Playwright Harness_",
        ]

        return "\n".join(lines)

    def summary_line(self, ticket_key: str, verdict: str, comment_preview: str) -> str:
        """Return the one-line output summary shown after posting."""
        preview = comment_preview[:60].replace("\n", " ")
        return (
            f"✓ JIRA ticket {ticket_key} updated\n"
            f"  Comment posted: {preview}\n"
            f"  Verdict:        {verdict}"
        )


def _load_report(path: str) -> dict:
    return json.loads(Path(path).read_text(encoding="utf-8"))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build JIRA QA report comment")
    parser.add_argument("--report", required=True, help="Path to JSON report file")
    args = parser.parse_args()

    data = _load_report(args.report)
    writer = JiraReportWriter()
    body = writer.build_comment(**data)
    print(body)
